### ISSUE TITLE
Safari redirect not working

### ISSUE THREAD

**Issue by grantmike** [trezm/cheerwine-issues#11]
Pressing https://jkbx.io/?room=49bd9b53-5d84-47da-98e6-c071801c4ce3 doesn't open up the relevant room post Fb login.

I land on home screen 
<img width="1432" alt="screen shot 2018-12-19 at 11 12 34 am" src="https://user-images.githubusercontent.com/26875636/50232470-028c7480-037f-11e9-90cf-2e73b8560583.png">

**Comment by trezm** [comment]
Resolved by https://github.com/trezm/cheerwine-web/pull/94
