### ISSUE TITLE
Lose scroll position in long chat when hitting search and returning to chat

### ISSUE THREAD

**Issue by will-weiss** [trezm/cheerwine-issues#22]
**Describe the bug**

I lose my scroll position in long chat when hitting search and returning to chat. That is, if I'm at the bottom (most recent) part of the chat, hit search, then hit chat I'm brought to the top (least recent) part of the chat.

**To Reproduce**
1. Go to a room
2. Enter a bunch of chat messages
3. Click 🔎
4. Click 💬
5. Observe that you're at the top of the chat

**Expected behavior**

I expect to be at the position I was looking at in the chat or at the bottom, but certainly not at the top.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trezm** [comment]
I literally noticed this when I was chatting with you yesterday lol. Definitely needs to be fixed.
