### ISSUE TITLE
Save as playlist!

### ISSUE THREAD

**Issue by will-weiss** [trezm/cheerwine-issues#28]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when my friends and I built a dope sequence of tracks and then they're lost to the ether.

**Describe the solution you'd like**

A save as playlist button! Click the button, give it a name - boom. New tracks added after that may or may not go into the playlist.

**Describe alternatives you've considered**

**Additional context**

**Comment by trezm** [comment]
Ah, yes... @medinab was going to try to do this, very important feature.

**Comment by medinab** [comment]
@will-weiss @trezm  Yup! Hoping to finish this up soon.

**Comment by trezm** [comment]
Shipped!
