### ISSUE TITLE
support apple music

### ISSUE THREAD

**Issue by peninakessler** [trezm/cheerwine-issues#3]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't log in using my Apple Music account. 

**Describe the solution you'd like**
Full support for listening on apple music.

**Describe alternatives you've considered**
Using a free tier spotify account, using my brother's spotify account.

**Comment by medinab** [comment]
yyyaaasssss +1

**Comment by trezm** [comment]
I'm not sure we can do this, @peninakessler I'm not familiar with apple music enough, but is it unlimited streaming like Spotify, or do you have to buy certain tracks?

Also -- do they have a web interface or is it all through itunes?

**Comment by trezm** [comment]
@gfogle, what do you think of the idea about having basically "loaner" spotify accounts that can stream but are cut off to only 20 minutes at a time?

**Comment by gfogle** [comment]
I like it. Wed have to examine both their User Agreement and the Developer Account UA to make sure we're not violating any terms.

Ideally, we'd programmatically sign up a new account or not let people "try it out!" if user's are currently using all the shared accounts.

Another interesting approach might be something like the [Play Button](https://developer.spotify.com/documentation/widgets/guides/adding-a-spotify-play-button/). Thinking out loud here, but the Room Creator would need to be Premium but we could use the API to create a playlist on their account and embed the Play Button for that playlist in the room. Then any user with a free account would be able to play that playlist. Not the same experience but definitely could be a teaser feature.
