### ISSUE TITLE
ability to type in lowercase

### ISSUE THREAD

**Issue by peninakessler** [trezm/cheerwine-issues#5]
**Is your feature request related to a problem? Please describe.**
sometimes i don't want to feel like i'm shouting 

**Describe the solution you'd like**
a button that lets me send a message with normal casing

**Describe alternatives you've considered**
dealing with it

**Comment by trezm** [comment]
agree -- we just need a font that isn't all caps (ours only has caps right now.)

**Comment by trezm** [comment]
Should be resolved by https://github.com/trezm/cheerwine-web/pull/120
