### ISSUE TITLE
Safari allows horizontal scrolling for long messages

### ISSUE THREAD

**Issue by trezm** [trezm/cheerwine-issues#9]
**Describe the bug**
Just brain dumping, but Mike had this issue. Long messages are bleeding out of their boxes in Safari.

**Comment by grantmike** [comment]
<img width="627" alt="screen shot 2018-12-18 at 2 36 18 pm" src="https://user-images.githubusercontent.com/26875636/50178598-fb0f9180-02d2-11e9-9438-0f8ce31c1ff5.png">

**Comment by trezm** [comment]
Resolved by https://github.com/trezm/cheerwine-web/pull/94
